api_platform:
    title: 'Functional Stability API'
    description: 'This API provides endpoints to get functional stability for for distributed information systems'
    version: '1.0.0'
    defaults:
        extra_properties:
            rfc_7807_compliant_errors: true

    formats:
        json: [ 'application/json' ]
        graphql: [ 'application/graphql' ]
        jsonld:   ['application/ld+json']

    error_formats:
        jsonproblem: [ 'application/problem+json' ]

    resource_class_directories:
        - '%kernel.project_dir%/src/FunctionalStability/Domain/Entity'