App\FunctionalStability\Domain\DTO\SimpleSearchDTO:
  properties:
    nodes:
      - NotNull: ~
      - NotBlank: ~
    edges:
      - NotNull: ~
    targetProbability:
      - NotNull: ~
      - NotBlank: ~
      - Type:
          type: float
