resources:
  App\FunctionalStability\Domain\Entity\FunctionalStability:
    operations:
      ApiPlatform\Metadata\Get: ~
      simple_search:
        uriTemplate: '/functional_stability/simple_search'
        class: 'ApiPlatform\Metadata\Post'
        input: 'App\FunctionalStability\Domain\DTO\SimpleSearchDTO'
        processor: 'App\FunctionalStability\Application\Processor\SimpleSearchProcessor'
      ApiPlatform\Metadata\Post:
        uriTemplate: '/functional_stability/structural_transformation'
        input: 'App\FunctionalStability\Domain\DTO\SimpleSearchDTO'
        processor: 'App\FunctionalStability\Application\Processor\StructuralTransformationProcessor'
