resources:
  App\FunctionalStability\Domain\Entity\FunctionalStability:
    operations:
      ApiPlatform\Metadata\Post:
        input: 'App\FunctionalStability\Domain\DTO\SimpleSearchDTO'
        processor: 'App\FunctionalStability\Application\Processor\SimpleSearchProcessor'
